# ndarray

: N차원 배열 객체, N-Dimensional Array

Numpy에서 ndarray 선형대수 연산, 다양한 집합 연산 지원

In [1]:
import numpy as np

list_data1 = [1,2,3]
list_data2 = [[1,2,3], [2,3,4]]

# array함수
array1 = np.array(list_data1)
array2 = np.array(list_data2)

In [2]:
# 1차원 ndarray
print(array1)
print(type(array1))

# array함수 인자에 ndarray 입력
print(np.array(array1))
print(type(np.array(array1)))

[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [3]:
# 2차원 ndarray
print(array2)
print(type(array2))

# array함수 인자에 ndarray 입력
print(np.array(array2))
print(type(np.array(array2)))

[[1 2 3]
 [2 3 4]]
<class 'numpy.ndarray'>
[[1 2 3]
 [2 3 4]]
<class 'numpy.ndarray'>


In [4]:
# 차원과 shape
"""
차원은 ndarray.ndim을 통해 확일할 수 있으며,
shape은 ndarray.shape를 통해 확인할 수 있습니다.
"""
print(array1.ndim)
print(array1.shape)

print(array2.ndim)
print(array2.shape)

1
(3,)
2
(2, 3)


In [5]:
test_list = [[1,2], [4,5,6]]
test_array = np.array(test_list)

print(test_array)
print(test_array.ndim)
print(test_array.shape)

[list([1, 2]) list([4, 5, 6])]
1
(2,)


In [6]:
print(test_array[0])
print(test_array[1])

[1, 2]
[4, 5, 6]


In [7]:
list_data = [[1,2,3]]
array_data = np.array(list_data)
print(array_data)
print(f'Shape: {array_data.shape}')
print(f'차원: {array_data.ndim}차원')

[[1 2 3]]
Shape: (1, 3)
차원: 2차원


## 1. type

ndarray 내의 데이터 값은 Number, String, Bool 자료형 등 모두 가능합니다.

숫자형의 경우 int(8bit, 16bit, 32bit), unsigned int(8bit, 16bit, 32bit), float형(16bit, 32bit, 64bit, 128bit), 더 큰 숫자값이나 정밀도를 위한 commplex 타입도 제공하고 있습니다.

In [8]:
list_data = ["문자열", "데이터", "확인"]

print(np.array(list_data))

['문자열' '데이터' '확인']


In [9]:
list_data = ["문자열", 123, "확인"]

print(np.array(list_data))

['문자열' '123' '확인']


In [10]:
list_data = [0.5, 123, 10.6]

print(np.array(list_data))

[  0.5 123.   10.6]


### dtype

`ndarray.dtype`을 통해 ndarray의 데이터 타입을 확인할 수 있습니다.

In [11]:
# ndarray.dtype - ndarray 내의 데이터 타입 확인
list_data = [[1,2,3], [2,3,4]]
array_data = np.array(list_data)

print(array_data)
print(array_data.dtype) # int32

[[1 2 3]
 [2 3 4]]
int32


### astype()

`ndarray.astype()`

In [12]:
array_int_data = np.array([1,2,3])
print(f'type: {array_int_data.dtype}')
array_float_data = array_int_data.astype('float64')
print(f'type: {array_float_data.dtype}')

array_int_data = array_float_data.astype('int32')
print(f'type: {array_int_data.dtype}')

array_float_data = np.array([1.3, 2.6, 3.3])
print(f'type: {array_float_data.dtype}')
print(array_float_data)

array_int_data = array_float_data.astype('int32')
print(f'type: {array_int_data.dtype}')
print(array_int_data)

type: int32
type: float64
type: int32
type: float64
[1.3 2.6 3.3]
type: int32
[1 2 3]


## 2. axis 축

ndarry는 행열의 개념이 아닌 axis0, axis1, axis2인 axis단위로 부여됩니다.

> **1차원 배열**일 때,
> - axis0 : 열방향

> **2차원 배열**일 때,
> - axis0 : 행방향
> - axis1 : 열방향

![](../assets/narray.png)

## 3. sum

In [13]:
array_data = np.array([[1,2,3], [4,5,6]])

print(array_data.sum()) # 각 요소의 총합
print(array_data.sum(axis=0)) # ↓행방향의 총합
print(array_data.sum(axis=1)) # →열방향의 총합

21
[5 7 9]
[ 6 15]


## 4. 초기값 생성

ndarray를 편리하게 생성하는 방법으로 `arange(), zeros(), ones()`함수를 사용할 수 있습니다.

위의 3가지 초기값을 생성하는 방법은 주로 테스트용으로 데이터를 생성하거나, 대규모의 데이터를 일괄적으로 초기화해야할 경우에 사용됩니다.

1. arange
: arange의 경우에는 우리가 파이썬에서 사용했던 range와 동일하다고 생각하시면 됩니다.

In [14]:
array_data = np.arange(10)
print(array_data)

array_data = np.arange(1, 10)
print(array_data)

array_data = np.arange(1, 10, 2)
print(array_data)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


2. zeros

: 정해진 shape로 배열의 내부에 값을 0으로 초기값을 생성합니다.

In [15]:
# 1차원 배열
zero_array = np.zeros(3, dtype='int32')
print(zero_array)
print(zero_array.shape)
print(zero_array.ndim)

# 2차원 배열
zero_array = np.zeros((3, 5), dtype='int32')
print(zero_array)
print(zero_array.shape)
print(zero_array.ndim)

# 3차원 배열
zero_array = np.zeros((3, 3, 2))
print(zero_array.dtype)
print(zero_array)
print(zero_array.shape)
print(zero_array.ndim)

[0 0 0]
(3,)
1
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
(3, 5)
2
float64
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
(3, 3, 2)
3


3. ones
: 정해진 shape로 배열의 내부에 값을 1로 초기값을 생성합니다.

In [16]:
# 1차원 배열
ones_array = np.ones(3)
print(zero_array.dtype)
print(ones_array)
print(ones_array.shape)
print(ones_array.ndim)

# 2차원 배열
ones_array = np.zeros((3, 5))
print(ones_array)
print(ones_array.shape)
print(ones_array.ndim)

# 3차원 배열
ones_array = np.zeros((3, 3, 2))
print(ones_array)
print(ones_array.shape)
print(ones_array.ndim)

float64
[1. 1. 1.]
(3,)
1
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(3, 5)
2
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
(3, 3, 2)
3


## 6. reshape

reshape()는 ndarray의 형태를 변환합니다.

In [17]:
array_data = np.arange(10)
print(array_data)

# reshape
trans_array_data = array_data.reshape(2, 5)
print(trans_array_data)
print(f'Shape: {trans_array_data.shape}')

print(trans_array_data.reshape(3,3)) # ValueError: cannot reshape array of size 10 into shape (3,3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
Shape: (2, 5)


ValueError: cannot reshape array of size 10 into shape (3,3)

In [18]:
print(trans_array_data.reshape(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


**axis=-1**

우리는 axis인자에 -1을 줌으로써 변형에 대해서 다소 자유로워질 수 있습니다.

In [19]:
# 1차원 리스트를 2차원 리스트로 변환 - 가변인자 사용
data_list = list(range(1, 10))
data_array = np.array(data_list)

print(data_array)
print(f'Shape: {data_array.shape}')

reshape_array = data_array.reshape(-1, 3)
print(reshape_array)
print(f'Shape: {reshape_array.shape}')

[1 2 3 4 5 6 7 8 9]
Shape: (9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)


In [20]:
data_array = np.arange(1, 10, 2)
print(data_array)
print(f'Shape: {data_array.shape}')

data_array1 = data_array.reshape(-1, 1)
data_array2 = data_array.reshape(-1,)

print(data_array1.shape)
print(data_array2.shape)

[1 3 5 7 9]
Shape: (5,)
(5, 1)
(5,)


In [21]:
print(data_array1)
print(data_array2)

[[1]
 [3]
 [5]
 [7]
 [9]]
[1 3 5 7 9]
