In [1]:
import numpy as np

# ndarray indexing

## 1. 단일 인덱싱

단일 인덱싱 방식은 파이썬 리스트와 동일합니다.

In [2]:
array = np.arange(1, 10)
print(array[0])
print(array[-1])

1
9


## 2. 슬라이싱

슬라이싱도 파이썬 리스트와 동일합니다.

⚠️다만, 차이점으로는 이중리스트를 진행하면서 발생합니다.

In [3]:
array_data = array.reshape(3, -1)
print(array_data)

print(array_data[0:3, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]
 [8]]


## 3. 팬시 인덱싱, Fancy Indexing

팬시 인덱싱은 리스트나 ndarray로 인덱스 집합을 지정하면 해당 값을 반환하는 방식입니다.

In [4]:
print(array_data)

array_data = array_data.reshape(-1,)
print(array_data)
print(array_data[ [1, 3, 5] ])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[2 4 6]


## 4. 불린 인덱싱, Boolean Indexing

불린 인덱싱은 조건 필터링과 검색을 동시에 할 수 있기 때문에 자주 사용되는 인덱싱 방식입니다.

In [5]:
# 불린 인덱싱을 사용하지X
result = []
for i in range(len(array_data)):
    if array_data[i] % 3 == 0:
        result.append(array_data[i])

# print(result) - 리스트 결과값
result = np.array(result)
print(result)
print(type(result))

# 사용O
print(array_data[array_data % 3 == 0])

[3 6 9]
<class 'numpy.ndarray'>
[3 6 9]
