In [1]:
import numpy as np

# Sort

- np.sort() : 원본 행렬은 그대로 유지하고 정렬된 행렬값 반환
- ndarray.sort() : 원본 행렬을 정렬하고 반환값 None

In [2]:
array = np.array([1,3,6,4,5,2,9,8,7])

sort_array = np.sort(array)
print(sort_array)

array = np.array([1,3,6,4,5,2,9,8,7])
array.sort()
print(array)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [3]:
# 2차원 배열에서 sort()
list_data = [[5,1,3], [2,6,4]]
array = np.array(list_data)
print(array)
sort_array = np.sort(array)
print(sort_array)

# 2차원 배열 - axis정렬
print(array)
print(np.sort(array, axis=1)) #axis1에 대한 정렬
print(np.sort(array, axis=0)) #axis0에 대한 정렬

[[5 1 3]
 [2 6 4]]
[[1 3 5]
 [2 4 6]]
[[5 1 3]
 [2 6 4]]
[[1 3 5]
 [2 4 6]]
[[2 1 3]
 [5 6 4]]


-----------------------------------------------------

# 선형대수 연산

## 1. 행렬 내적

행렬의 내적은 A · B라고 하였을 때,

`A shape: (a, b)`

`B shape: (c, d)`라면,

**b와 c의 값이 같아야합니다.**

그렇게 되면 (a, c) shape의 값이 나옵니다.

사용법은 다음과 같습니다.

1. np.dot(배열1, 배열2)

2. 배열1.dot(배열2)

In [4]:
array1 = np.array([[1,2,3], [4,5,6]])
array2 = np.array([[7,8], [9,10], [11,12]])

print(np.dot(array1, array2))
print(array1.dot(array2))

[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]


## 2. 전치 행렬

array의 전치 행렬은 그 행렬을 대각선을 기준으로 하여 뒤집어 나온 값입니다. (대각선은 오른쪽 상단에서 왼쪽 하단의 모양입니다.)

사용법은 다음과 같습니다.

1. np.transpose(행렬)
2. 행렬.transpose()

1번의 경우는 원본에 영향을 주지 않고 결과값을 반환합니다.

2번의 경우는 원본에 값이 변화됩니다.

전치 행렬의 예는 다음과 같습니다.
![](../assets/ndarray_transpose.png)
<sub>(출처: 위키백과-전치행렬)</sub>

In [5]:
print(array)

trans_array = np.transpose(array) #전치행렬
print(trans_array)

test = array.transpose()
print(test)

[[5 1 3]
 [2 6 4]]
[[5 2]
 [1 6]
 [3 4]]
[[5 2]
 [1 6]
 [3 4]]
