# axis 축

ndarray는 행열의 개념이 아닌 axis0, axis1, axis2인 axis단위로 부여됩니다.

**1차원 배열**일 때,

- axis0: 열방향

**2차원 배열**일 때,

- axis0: 행방향

- axis1: 열방향

**3차원 배열**일 때,

- axis0: 높이

- axis1: 행방향

- axis2: 열방향




![ndarray axis](./assets/numpy_axis.png)

In [1]:
import numpy as np

data = [
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ],
    [
        [25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]
    ]
]

arr = np.array(data)
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
