# 원소 정렬, 추가, 제거

## 1. 정렬

### - sort

기본으로 정렬은 오름차순이 됩니다.

In [5]:
import numpy as np

data = [2,5,3,1,7,5,9,0]
arr = np.array(data)
print(f"정렬 전: {arr}")

arr = np.sort(arr)
print(f"정렬 후: {arr}")

# 내림차순
print(f"내림차순: {arr[::-1]}")

정렬 전: [2 5 3 1 7 5 9 0]
정렬 후: [0 1 2 3 5 5 7 9]
내림차순: [9 7 5 5 3 2 1 0]


In [4]:
# 2차원 배열에서 sort()
data = [[5,1,3], [2,6,4]]
array = np.array(data)
print(array)
sort_array = np.sort(array)
print(sort_array)

# 2차원 배열 - axis정렬
print(array)
print(np.sort(array, axis=1)) #axis1에 대한 정렬
print(np.sort(array, axis=0)) #axis0에 대한 정렬

[[5 1 3]
 [2 6 4]]
[[1 3 5]
 [2 4 6]]
[[5 1 3]
 [2 6 4]]
[[1 3 5]
 [2 4 6]]
[[2 1 3]
 [5 6 4]]
