# 배열의 원소

## 원소 정렬, 추가, 제거

### 1. 정렬

#### - sort()

기본으로 정렬은 오름차순이 됩니다.

- `np.sort()`: 원본 행렬 그대로 유지하고 정렬된 행렬값 반환   (->Python에서의 sorted와 유사)

- `ndarray.sort()`: 원본 행렬을 정렬하고 반환값 None   (-> Python에서의 sort와 유사)

In [1]:
import numpy as np

data = [2,5,3,1,7,5,9,0]
arr = np.array(data)
print(f"정렬 전: {arr}")

arr = np.sort(arr)
print(f"정렬 후: {arr}")

# 내림차순
print(f"내림차순: {arr[::-1]}")

정렬 전: [2 5 3 1 7 5 9 0]
정렬 후: [0 1 2 3 5 5 7 9]
내림차순: [9 7 5 5 3 2 1 0]


In [2]:
# 2차원 배열에서 sort()
data = [[5,1,3], [2,6,4]]
array = np.array(data)
print(array)
sort_array = np.sort(array)
print(sort_array)

# 2차원 배열 - axis정렬
print("==================")
print(array)
print("==================")
print(np.sort(array, axis=1)) #axis1에 대한 정렬
print(np.sort(array, axis=0)) #axis0에 대한 정렬

[[5 1 3]
 [2 6 4]]
[[1 3 5]
 [2 4 6]]
[[5 1 3]
 [2 6 4]]
[[1 3 5]
 [2 4 6]]
[[2 1 3]
 [5 6 4]]


### 2. 원소 추가

#### - concatenate()

2개 이상의 배열을 이어 붙여서 하나로 합칠 수 있습니다.

`np.concatenate((arr1, arr2, ...), axis=0, out=None)`

axis: [선택사항] 배열이 결합되는 축. 축이 None이면 1차원 배열. default=0

out: [선택사항] 결합된 배열의 출력 모양을 나타냄. 작성한 모양은 출력 배열과 동일해야 함



In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[1 2 3 4 5 6]


In [4]:
data1 = [[5,1,3], [2,6,4]]
data2 = [[2,3,4], [4,5,6]]

arr1 = np.array(data1)
arr2 = np.array(data2)

print(np.concatenate((arr1, arr2)))
print("==========================")
print(np.concatenate((arr1, arr2), axis=1))
print("==========================")


data1 = [[5,1,3], [2,6,4]]
data2 = [[2,3,4], [4,5,6], [5,4,3]]

arr1 = np.array(data1)
arr2 = np.array(data2)

# 크기 주의할 점 (크기가 맞아야 합쳐짐)
# print(np.concatenate((arr1, arr2), axis=1))
# print("==========================")

[[5 1 3]
 [2 6 4]
 [2 3 4]
 [4 5 6]]
[[5 1 3 2 3 4]
 [2 6 4 4 5 6]]


### 3. 원소 제거

#### - delete()

`np.delete(arr, obj, axis=None)` 축을 따라 하위 배열이 삭제된 새 배열을 반환

obj: 슬라이스, 정수 또는 정수 배열. 지정된 축을 따라 제거할 하위 배열의 인덱스

axis: [선택사항] default=None

In [5]:
data = [[5,1,3], [2,6,4]]
arr = np.array(data)

print(f"삭제 이전\n{arr}")

arr = np.delete(arr, 1) # axis을 어떻게 주느냐에 따라 결과가 달라짐 / 줄때 안줄때

print(f"삭제 이후\n{arr}")

삭제 이전
[[5 1 3]
 [2 6 4]]
삭제 이후
[5 3 2 6 4]


In [6]:
data1 = [[5,1,3], [2,6,4]]
data2 = [[2,3,4], [4,5,6]]

arr1 = np.array(data1)
arr2 = np.array(data2)

arr =np.concatenate((arr1, arr2))

print(f"삭제 이전\n{arr}")

arr = np.delete(arr, 1) # axis을 어떻게 주느냐에 따라 결과가 달라짐 / 줄때 안줄때

print(f"삭제 이후\n{arr}")

삭제 이전
[[5 1 3]
 [2 6 4]
 [2 3 4]
 [4 5 6]]
삭제 이후
[5 3 2 6 4 2 3 4 4 5 6]


## 배열의 사칙연산

배열의 덧셈/뺄셈은 같은 위치에 있는 것끼리 덧셈/뺄셈이 이뤄집니다.

In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2) # 같은 위치의 데이터만 산술연산됨

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[4,5,6], [-3,-2,-1]])

print(arr1 + arr2)

[5 7 9]
[[5 7 9]
 [1 3 5]]


In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 - arr2)

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[4,5,6], [-3,-2,-1]])

print(arr1 - arr2)

[-3 -3 -3]
[[-3 -3 -3]
 [ 7  7  7]]


In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 * arr2)

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[4,5,6], [-3,-2,-1]])

print(arr1 * arr2)

[ 4 10 18]
[[  4  10  18]
 [-12 -10  -6]]


In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 / arr2)

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[4,5,6], [-3,-2,-1]])

print(arr1 / arr2)

[0.25 0.4  0.5 ]
[[ 0.25        0.4         0.5       ]
 [-1.33333333 -2.5        -6.        ]]


위와 같이 덧셈, 뺄셈 뿐만이 아니라 사칙연산에 대해서 동일하게 작용하는 것을 알 수 있습니다.

`*`는 행렬곱이 아닌 원소끼리의 사칙연산이라는 것을 알 수 있습니다.