# 배열의 원소

## 원소 정렬, 추가, 제거

### 1. 정렬

#### - sort()

기본으로 정렬은 오름차순이 됩니다.

In [1]:
import numpy as np

data = [2,5,3,1,7,5,9,0]
arr = np.array(data)
print(f"정렬 전: {arr}")

arr = np.sort(arr)
print(f"정렬 후: {arr}")

# 내림차순
print(f"내림차순: {arr[::-1]}")

정렬 전: [2 5 3 1 7 5 9 0]
정렬 후: [0 1 2 3 5 5 7 9]
내림차순: [9 7 5 5 3 2 1 0]


In [2]:
# 2차원 배열에서 sort()
data = [[5,1,3], [2,6,4]]
array = np.array(data)
print(array)
sort_array = np.sort(array)
print(sort_array)

# 2차원 배열 - axis정렬
print(array)
print(np.sort(array, axis=1)) #axis1에 대한 정렬
print(np.sort(array, axis=0)) #axis0에 대한 정렬

[[5 1 3]
 [2 6 4]]
[[1 3 5]
 [2 4 6]]
[[5 1 3]
 [2 6 4]]
[[1 3 5]
 [2 4 6]]
[[2 1 3]
 [5 6 4]]


### 2. 원소 추가

#### - concatenate()

2개 이상의 배열을 이어 붙여서 하나로 합칠 수 있습니다.

`np.concatenate((arr1, arr2, ...), axis=0, out=None)`

axis: [선택사항] 배열이 결합되는 축. 축이 None이면 1차원 배열. default=0

out: [선택사항] 결합된 배열의 출력 모양을 나타냄. 작성한 모양은 출력 배열과 동일해야 함



In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[1 2 3 4 5 6]


### 3. 원소 제거

#### - delete()

`np.delete(arr, obj, axis=None)` 축을 따라 하위 배열이 삭제된 새 배열을 반환

obj: 슬라이스, 정수 또는 정수 배열. 지정된 축을 따라 제거할 하위 배열의 인덱스

axis: [선택사항] default=None

In [4]:
print(f"삭제 이전: {arr}")

arr = np.delete(arr, 1) # return method

print(f"삭제 이후: {arr}")

삭제 이전: [1 2 3 4 5 6]
삭제 이후: [1 3 4 5 6]


In [5]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(f"삭제 이전: {arr}")

arr = np.delete(arr, [1, 3, 4]) # return method

print(f"삭제 이후: {arr}")

삭제 이전: [1 2 3 4 5 6]
삭제 이후: [1 3 6]


## 배열의 사칙연산

배열의 덧셈/뺄셈은 같은 위치에 있는 것끼리 덧셈/뺄셈이 이뤄집니다.

In [6]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[4,5,6], [-3,-2,-1]])

print(arr1 + arr2)

[5 7 9]
[[5 7 9]
 [1 3 5]]


In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 - arr2)

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[4,5,6], [-3,-2,-1]])

print(arr1 - arr2)

[-3 -3 -3]
[[-3 -3 -3]
 [ 7  7  7]]


In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 * arr2)

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[4,5,6], [-3,-2,-1]])

print(arr1 * arr2)

[ 4 10 18]
[[  4  10  18]
 [-12 -10  -6]]


In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 / arr2)

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[4,5,6], [-3,-2,-1]])

print(arr1 / arr2)

[0.25 0.4  0.5 ]
[[ 0.25        0.4         0.5       ]
 [-1.33333333 -2.5        -6.        ]]


위와 같이 덧셈, 뺄셈 뿐만이 아니라 사칙연산에 대해서 동일하게 작용하는 것을 알 수 있습니다.

`*`는 행렬곱이 아닌 원소끼리의 사칙연산이라는 것을 알 수 있습니다.

### 1. sum()

배열의 원소들의 총합을 구하려면 sum을 이용할 수 있습니다.

2차원 이상이 되었을 때부터는 `axis`를 통해서 축을 정해줄 수 있습니다.

In [10]:
arr = np.array([1, 2, 3])

print(np.sum(arr))

arr = np.array([[1,2,3], [4,5,6]])

print(np.sum(arr))

6
21


### 2. max()

축을 따라 최댓값을 반환합니다.

2차원 이상이 되었을 때부터는 `axis`를 통해서 축을 정해줄 수 있습니다.

In [11]:
arr = np.array([1, 2, 3])

print(np.max(arr))

arr = np.array([[1,2,3], [4,5,6]])

print(np.max(arr))
print(arr.max())


data = [[1,2,3], [4,5,6], [7,8,9]]
arr = np.array(data)
print(np.max(arr, axis=0))
print(np.max(arr, axis=1))
print(arr.max())

3
6
6
[7 8 9]
[3 6 9]
9


### 3. min()

축을 따라 최솟값을 반환합니다.

In [12]:
arr = np.array([1, 2, 3])

print(np.min(arr))

arr = np.array([[1,2,3], [4,5,6]])

print(np.min(arr))
print(arr.min())


data = [[1,2,3], [4,5,6], [7,8,9]]
arr = np.array(data)
print(np.min(arr, axis=0))
print(np.min(arr, axis=1))
print(arr.min())

1
1
1
[1 2 3]
[1 4 7]
1


### 4. mean()

`mean()` 함수는 지정된 축을 따라 산술 평균을 계산합니다.

In [13]:
arr = np.array([1, 2, 3])

print(np.mean(arr))

arr = np.array([[1,2,3], [4,5,6]])

print(np.mean(arr))
print(arr.mean())


data = [[1,2,3], [4,5,6], [7,8,9]]
arr = np.array(data)
print(np.mean(arr, axis=0))
print(np.mean(arr, axis=1))
print(arr.mean())

2.0
3.5
3.5
[4. 5. 6.]
[2. 5. 8.]
5.0


### 5. std()

`std()` 함수는 지정된 축을 따라 표준 편차를 계산합니다.

In [14]:
arr = np.array([1, 2, 3])

print(np.std(arr))

arr = np.array([[1,2,3], [4,5,6]])

print(np.std(arr))
print(arr.std())


data = [[1,2,3], [4,5,6], [7,8,9]]
arr = np.array(data)
print(np.std(arr, axis=0))
print(np.std(arr, axis=1))
print(arr.std())

0.816496580927726
1.707825127659933
1.707825127659933
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]
2.581988897471611


### 6. prod()

`prod()`함수는 주어진 축에서 배열 요소의 곱을 반환합니다.

In [15]:
arr = np.array([1, 2, 3])

print(np.prod(arr))

arr = np.array([[1,2,3], [4,5,6]])

print(np.prod(arr))
print(arr.prod())


data = [[1,2,3], [4,5,6], [7,8,9]]
arr = np.array(data)
print(np.prod(arr, axis=0))
print(np.prod(arr, axis=1))
print(arr.prod())

6
720
720
[ 28  80 162]
[  6 120 504]
362880


### 7. dot()

`dot()`함수는 두 배열의 내적을 구해줍니다.

In [16]:
arr1 = np.array([[2,3], [4,5]])
arr2 = np.array([[2,0], [0,3]])
print(arr1.dot(arr2))

[[ 4  9]
 [ 8 15]]


### 8. np.matmul()

`np.matmul()` 함수는 두 배열의 행렬 곱을 구해줍니다.

In [17]:
arr1 = np.array([[2,3], [4,5]])
arr2 = np.array([[2,0], [0,3]])
print(np.matmul(arr1, arr2))

[[ 4  9]
 [ 8 15]]


<sub>**심화]**</sub>
<div style="border-left-style: solid;
  border-left-color: coral;
  padding-left: 10px;">
    <strong>dot 함수</strong><br/>
    dot함수에 대해서 조금 더 알아보도록 하겠습니다.<br/>
    dot 함수를 이해하기 위해서는 document를 보는 것이 최적입니다.<br/>
    <a href="https://numpy.org/doc/stable/reference/generated/numpy.dot.html">https://numpy.org/doc/stable/reference/generated/numpy.dot.html</a>
</div>

- If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.

> 번역]
>
> a 또는 b가 0차원(스칼라)이면 곱하는 것과 동일하며 numpy.multiply(a, b) 또는 a * b를 사용하는 것이 선호됩니다.

- If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

> 번역]
>
> a와 b가 모두 1차원 배열이면 벡터의 내적입니다(복소수 켤레 없음).

- If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

> 번역]
>
> a와 b가 모두 2차원 배열이면 행렬 곱셈이지만 matmul이나 a @ b를 사용하는 것이 좋습니다.

- If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

> 번역]
>
> a가 N차원 배열이고 b가 1차원 배열이면 a와 b의 마지막 축에 대한 합입니다.

- If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b

> 번역]
>
> a가 N차원 배열이고 b가 M차원 배열이면(여기서 M>=2) a의 마지막 축과 b의 마지막에서 두 번째 축에 대한 합입니다.

In [18]:
arr1 = np.arange(2*3*4).reshape((2,3,4))
arr2 = np.arange(2*3*4)[::-1].reshape((2,4,3)) # 2, 3, 4로 dot 진행시에 마지막 정의에 틀리기에 ValueError

print(arr1)
print(arr2)

print(arr1.shape)
print(arr2.shape)

result = arr1.dot(arr2)
print(result.shape)
print(result)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[23 22 21]
  [20 19 18]
  [17 16 15]
  [14 13 12]]

 [[11 10  9]
  [ 8  7  6]
  [ 5  4  3]
  [ 2  1  0]]]
(2, 3, 4)
(2, 4, 3)
(2, 3, 2, 3)
[[[[  96   90   84]
   [  24   18   12]]

  [[ 392  370  348]
   [ 128  106   84]]

  [[ 688  650  612]
   [ 232  194  156]]]


 [[[ 984  930  876]
   [ 336  282  228]]

  [[1280 1210 1140]
   [ 440  370  300]]

  [[1576 1490 1404]
   [ 544  458  372]]]]


![dot_func01](./assets/numpy_dot01.png)

![dot_func02](./assets/numpy_dot02.png)

<sub>**심화]**</sub>
<div style="border-left-style: solid;
  border-left-color: coral;
  padding-left: 10px;">
    <strong>dot와 matmul 차이</strong><br/>
    matmul함수는 스칼라에에 의한 곱셈은 허용되지 않습니다. (대신, * 연산자를 사용해주세요.)<br/>
    shape(n,k)와 shape(k,m)을 matmul하면 (n,m)의 shape을 가진 배열이 나옵니다.<br/>
</div>

In [19]:
# 3차원 이상의 배열 dot와 matmul의 shape 차이

arr1 = np.ones([9, 5, 7, 4])
arr2 = np.ones([9, 5, 4, 3])
# dot와 동일하게 A배열의 마지막 축의 값과 B의 마지막에서 두번째 축의 값이 같아야함

print(f"dot Func Shape: {arr1.dot(arr2).shape}") # (9, 5, 7, 9, 5, 3)
print(f"dot Func Shape: {np.matmul(arr1, arr2).shape}") # (9, 5, 7, 3)

dot Func Shape: (9, 5, 7, 9, 5, 3)
dot Func Shape: (9, 5, 7, 3)
