# 배열의 형태 변경하기

1차원의 행열을 2차원으로 변경하여 사용하거나, 반대로 사용할 수도 있습니다.

## arr.reshape()

기존 배열의 모양을 바꿀 수 있습니다.

주의해야할 사항은 변경 전과 변경 후의 배열에는 각각 동일한 수의 원소가 있어야 합니다.

In [1]:
import numpy as np

data = [1, 2, 3, 4, 5, 6]
arr = np.array(data)

arr = arr.reshape(2, -1)
print(arr)
print(arr.ndim) # 차원 변경
print(arr.shape) # 모양 변경

[[1 2 3]
 [4 5 6]]
2
(2, 3)


## numpy.reshape()

numpy.reshape(재구성할 배열, 변경할 shape, order)

order = 'C', 'F', 'A'가 있으며,

C: C언어 방식

F: Fortain 방식

A: 메모리에 따라 C와 F 중 자동 선택

<sub>**참고]**</sub>
<div style="border-left-style: solid;
  border-left-color: coral;
  padding-left: 10px;">
    C는 마지막 차원 인덱스가 가장 빠르게 변경되고 첫번째 차원 인덱스가 가장 느리게 변경됩니다.<br/>
    Fortran은 첫번째 차원 인덱스가 가장 빠르게 변경되고 마지막 차원 인덱스가 가장 느리게 변경됩니다.
</div>

`shape`에 인자 -1은 배열의 길이와 남은 차원을 유추해서 자동으로 형태가 변경됩니다.

In [2]:
arr = np.reshape(arr, -1)
print(arr)

[1 2 3 4 5 6]


In [3]:
import numpy as np

data = [0, 1, 2, 3]
arr = np.array(data)
brr = arr.reshape(2, -1) # reshape 얇은 복사
crr = brr.copy() # numpy에서 copy는 깊은 복사가 이뤄짐
brr[0,0] = 3
print(arr)
print(crr)
drr = np.resize(arr, 3)
print(drr)
# arr.resize(3) # 얇은 복사로 인해 메모리 문제가 생겨 resize 안된다고 나옴
print(arr)

data = [[0, 1], [2, 3]]
arr = np.array(data)
arr[0, 0] = 3
print(arr)
arr.resize(3)
print(arr)

[3 1 2 3]
[[0 1]
 [2 3]]
[3 1 2]
[3 1 2 3]
[[3 1]
 [2 3]]
[3 1 2]


In [4]:
# reshape는 얇은 복사가 이뤄진다
data = [1, 2, 3, 4, 5, 6]
arr = np.array(data)

brr = np.reshape(arr, (2, -1))
brr[0, 0] = 7
print(arr)

brr = arr.reshape((2, -1))
brr[0, 0] = 9
print(arr)

[7 2 3 4 5 6]
[9 2 3 4 5 6]


## Indexing & Slicing

Numpy에서도 인덱싱과 슬라이싱이 동일하게 있습니다.

다만, 인덱싱부터 방법이 살짝 다르니 해당 부분만 이해한다면 동일합니다.

위에 알게 모르게 사용을 했기 때문에 이미 눈치를 채셨을거라 봅니다.

In [5]:
data = [[5, 6, 7], [8, 9, 10]]
arr = np.array(data)
print(arr[0,1]) # 6
print(arr[1,0]) # 7

# Slicing
print(arr[1:, 1:]) # [[ 9 10]]
print(arr[0:, 1:]) # [[ 6 7 ] [ 9 10]]

print(arr[1:]) # [[ 8  9 10]]

6
8
[[ 9 10]]
[[ 6  7]
 [ 9 10]]
[[ 8  9 10]]


어떠한 분들은 `arr[0][1]`을 했을 때도 값이 나오는 것을 확인하고
되네?!라고 생각하실 것입니다.

`arr[0][1]`의 경우는 첫 번째 항을 반환 후에 열에 대한 데이터를 가져와야 하므로 `arr[0, 1]`보다 비효율적입니다.

### Fancy Indexing

팬시 인덱싱은 리스트나 ndarray로 인덱스 집합을 지정하면 해당 값을 반환하는 방식

In [6]:
data = list(range(1, 10))
arr = np.array(data)
print(arr)
print(arr[ [1, 3, 5] ])

[1 2 3 4 5 6 7 8 9]
[2 4 6]


### Boolean Indexing

불린 인덱싱은 조건 필터링과 검색을 동시에 할 수 있기 때문에 자주 사용되는 인덱싱 방식입니다.

In [7]:
data = list(range(1, 10))
arr = np.array(data)
print(arr[arr > 5])

# 조건을 변수에 담고 사용
arr = np.array(data)
if_data = arr > 5
print(f"조건 결과: {if_data}")
print(arr[if_data])

# &: and연산자 |: or 연산자
# 파이썬에서는 and와 or을 사용했는데 Numpy에서는 &와 |을 사용
if_data1 = arr > 5
if_data2 = arr <= 7
print(arr[if_data1 & if_data2])

[6 7 8 9]
조건 결과: [False False False False False  True  True  True  True]
[6 7 8 9]
[6 7]
