# Numpy


## 배열 얕은 복사, 깊은 복사

### 1. 얕은 복사

얕은 복사 방식은 새로운 객체를 복사를 하여 서로 다른 주소를 갖지만 동일한 데이터를 보고 있기 때문에 복사한 데이터를 변경하여도 이전의 데이터의 값도 변경됩니다.

`view 함수`

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])

copy_arr = arr.view()
print(f"데이터 변경전: {copy_arr}")

copy_arr[2] = 7
print(f"데이터 변경후: {copy_arr}")
print(f"원본 데이터: {arr}")

# 주소값 확인
print("복사 데이터 주소:", id(copy_arr))
print("원본 데이터 주소:", id(arr))

데이터 변경전: [1 2 3 4 5]
데이터 변경후: [1 2 7 4 5]
원본 데이터: [1 2 7 4 5]
복사 데이터 주소: 2973808754288
원본 데이터 주소: 2973809431728


### 2. 깊은 복사

깊은 복사 방식은 완전히 다른 복사본을 만드는 방식입니다.

깊은 복사를 했을 때 복사 데이터를 변경하여도 원본 데이터가 변경되지 않습니다.

In [2]:
arr = np.array([1,2,3,4,5])

copy_arr = arr.copy()
print(f"데이터 변경전: {copy_arr}")

copy_arr[2] = 7
print(f"데이터 변경후: {copy_arr}")
print(f"원본 데이터: {arr}")

# 주소값 확인
print("복사 데이터 주소:", id(copy_arr))
print("원본 데이터 주소:", id(arr))

데이터 변경전: [1 2 3 4 5]
데이터 변경후: [1 2 7 4 5]
원본 데이터: [1 2 3 4 5]
복사 데이터 주소: 2973813831600
원본 데이터 주소: 2973813831504


## 배열 쌓기

stack을 통해서 쌓을 수 있습니다.

세로로 쌓는 것은 `vstack`, 가로로 쌓는 것은 `hstack`입니다.

v는 vertically의 축약이며, h는 horizontally의 축약입니다.

### 1. np.vstack()

두 배열 이상을 세로로 쌓아 새로운 하나의 배열을 만들어 줍니다.

`numpy.vstack(tuple)`

인자로는 ndarray의 tuple이나 리스트가 되고, 배열은 첫 번째 축을 제외하고 모두 동일한 모양이어야 하며, 1차원 배열은 길이가 같아야 합니다.

In [3]:
arr1 = np.arange(2*3).reshape(2, 3)
arr2 = np.array([[4,3,5]])
arr3 = np.array([[3,3,3], [4,4,4], [5,5,5]])

result = np.vstack([arr1, arr2, arr3])
print(result)

[[0 1 2]
 [3 4 5]
 [4 3 5]
 [3 3 3]
 [4 4 4]
 [5 5 5]]


### np.hstack()

두 배열 이상을 가로로 쌓아 하나의 배열을 만들어 줍니다.

`numpy.hstack(tuple)`

인자로는 ndarray의 tuple이나 리스트가 되고, 배열은 두 번째 축을 제외하고 모두 동일한 모양이어야 하며, 1차원 배열은 길이가 같지 않아도 됩니다.

In [4]:
arr1 = np.arange(2*3).reshape(2, 3)
arr2 = np.array([[4], [3]])
arr3 = np.array([[3,3,3],[4,4,4]])

result = np.hstack([arr1, arr2, arr3])
print(result)

[[0 1 2 4 3 3 3]
 [3 4 5 3 4 4 4]]


## 배열 쪼개기

split을 통하여 분할할 수 있습니다.

### 1. np.vsplit()

배열을 세로로 나누어 여러 하위 배열로 분할합니다. (행방향)

`numpy.vsplit(array, indices_or_sections)`

> array: 원본 배열
>
> indices_or_sections: int 또는 나누고 싶은 행들 입력

In [5]:
arr = np.arange(6 * 4).reshape(6, 4)

arr1, arr2, arr3 = np.vsplit(arr, 3)
print(f"ARR1:\n{arr1}\n")
print(f"ARR2:\n{arr2}\n")
print(f"ARR3:\n{arr3}\n")

ARR1:
[[0 1 2 3]
 [4 5 6 7]]

ARR2:
[[ 8  9 10 11]
 [12 13 14 15]]

ARR3:
[[16 17 18 19]
 [20 21 22 23]]



In [6]:
# 나누고 싶은 행 지정하여 나누기

arr = np.arange(6 * 4).reshape(6, 4)

print(arr)

arr1, arr2, arr3, arr4 = np.vsplit(arr, (2,5,6))
print(f"ARR1:\n{arr1}\n")
print(f"ARR2:\n{arr2}\n")
print(f"ARR3:\n{arr3}\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
ARR1:
[[0 1 2 3]
 [4 5 6 7]]

ARR2:
[[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

ARR3:
[[20 21 22 23]]



### 2. np.hsplit()

배열을 가로로 나누어 여러 하위 배열로 분할합니다. (열방향)

`numpy.hsplit(array, indices_or_sections)`

> array: 원본 배열
>
> indices_or_sections: int 또는 나누고 싶은 행들 입력

방향만 다르기에 예제는 생략하겠습니다.