# 난수 생성

인공 신경망에 가중치를 무작위로 초기화 하거나, 데이터를 무작위 세트로 분할하거나, 데이터 세트를 무작위로 셔플하는 등에 활용됩니다.

In [1]:
import numpy as np

## 1. np.random.randint()

지정된 최솟값부터 최댓값 사이의 임의의 정수를 반환

`numpy.random.randint(low, high, size=None)`

> - low: [선택사항] int, 분포에서 가져올 가장 작은 정수
> 
> - high: int, 분포에서 가져올 가장 큰 정수. low를 생략시 0부터 high미만의 정수 반환
>
> - size: [선택사항] int or int로 이루어진 tuple, 출력 개수 혹은 shape, defualt=None으로 단일 값 반환

In [2]:
np.random.randint(100)

62

In [3]:
np.random.randint(100, size=10)

array([ 7, 45, 33, 65, 70, 92, 24, 36, 81, 91])

In [4]:
np.random.randint(100, size=(2,3,3))

array([[[95,  2, 99],
        [31, 69, 50],
        [13, 11, 96]],

       [[69,  1, 56],
        [55, 23, 78],
        [24, 47, 68]]])

## 2. np.random.rand()

주어진 shape의 임의 값을 반환. 0이상 1미만의 값 반환

`numpy.random.rand(d0, d1, ..., dn)`

> - d0, d1, ..., dn: [선택사항] 반환할 배열의 shape를 int로 입력

In [5]:
np.random.rand(2,3)

array([[0.49506019, 0.28577473, 0.85636716],
       [0.94634853, 0.08029125, 0.45285409]])

## 3. np.random.randn()

표준정규분포를 따르는 샘플 값 반환

> **표준정규분포**란?
>
> 평균이 0이고 분산이 1인 정규분포 N(0,1)를 표준정규분포라고 합니다.

In [6]:
np.random.randn(3,4)

array([[ 0.30181862,  0.11345989,  0.90120217,  0.52252191],
       [ 0.99161874, -1.44496703, -0.70860667,  0.40985144],
       [ 0.958808  ,  1.4183641 , -1.26213558, -0.84486563]])

## 4. np.random.shuffle()

배열을 무작위로 섞어서 제자리에서 시퀀스를 수정

이 함수는 다차원 배열의 첫 번째 축을 따른 배열만 섞습니다.

하위 배열 간의 순서는 변경되지만 그 안의 내용은 동일하게 유지됩니다.

In [7]:
arr = np.arange(10)
print(arr)

np.random.shuffle(arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[4 0 7 9 1 8 5 3 6 2]


## 5. np.random.choice()

주어진 int 또는 1차원 배열에서 무작위 샘플을 생성합니다.

`numpy.random.choice(a, size=None, replace=True, p=None)`

> a: int 또는 1차원 배열. int이면 임의 샘플이 a=np.arange(a)인 것처럼 생성됩니다.
> 
> size: [선택사항] int 또는 int의 tuple

int가 입력되면 반환값의 size, tuple이 입력되면 shape로 간주해 (m,n,k)일 때 m*n*k개의 샘플이 반환됩니다. 기본적으로 None으로, 이 경우 단일 값이 반환됩니다.

> replace: [선택사항] bool, 샘플의 중복 여부
>
> p: [선택사항] 1차원 배열. a의 각 항목과 관련된 확률입니다. 지정되지 않은 경우 샘플은 a의 모든 항목에 대해 균일한 분포를 가정합니다.

In [8]:
arr = np.random.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0])
print(arr)
print(arr.shape)

[3 0 3]
(3,)
