# 전치 행렬

행렬의 전치란 어떤 행렬의 행과 열을 바꿔주는 것을 말합니다

![전치행렬](./assets/numpy_transpose.png)

## 1. np.transpose()

배열의 축을 뒤집거나 바꾸어 수정된 배열을 반환합니다.

축이 두 개인 배열의 경우 transpose(arr)는 전치 행렬을 제공합니다.

`numpy.transpose(arr, axis=None)`

In [1]:
import numpy as np

arr = np.arange(1,7).reshape(3,2)
print(arr)

transpose_arr = np.transpose(arr)
print(transpose_arr)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [2]:
# reshape을 통해서 모양은 맞출 수 있지만, 내용값은 다름
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

## 2. T

ndarray.T는 전치된 배열입니다.

In [3]:
print(arr.T)

[[1 3 5]
 [2 4 6]]
