# 배열을 평평하게 하는 방법

## 1. flatten()

flatten()방식은 copy방식을 사용하여 깊은 복사로 진행됩니다.

하나의 차원으로 축소된 배열의 복사본을 반환합니다.

`ndarray.flatten(order='C')`

> order: [선택사항] default='C'
> - C: 행을 우선 평면화
> - F: 열을 우선 평면화

In [1]:
import numpy as np

arr = np.arange(1, 7).reshape(3,2)
print(arr)

flatten_arr = arr.flatten()
print(flatten_arr)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


## 2. ravel()

ravel()방식은 view방식을 사용하여 얕은 복사로 진행됩니다.

연속적인 평탄화된 배열을 반환합니다.

In [2]:
arr = np.arange(1, 7).reshape(3,2)
print(arr)

ravel_arr = np.ravel(arr)
print(ravel_arr)

# 얕은 복사 확인해보기
ravel_arr[3] = 100

print(arr)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[  1   2]
 [  3 100]
 [  5   6]]
