# Numpy 객체 저장 및 불러오기

## 1. 객체 저장하기

numpy 객체는 `.npy`, `.npz`, `.csv`, `.txt` 파일 등으로 저장되고 다시 로드하여 이용할 수 있습니다.

단일 ndarray 객체를 저장하려면 **np.save()**를 이용해 `.npy`파일로 저장합니다.

In [1]:
import numpy as np

# 단일 ndarry 객체 저장

arr = np.arange(1, 7)
np.save('./assets/test', arr) # assets폴더 안에 test.npy 파일 저장됨

하나의 파일에 둘 이상의 ndarray 객체를 저장하려면 **np.savez()**을 이용해 `.npz`파일로 저장합니다.

In [2]:
arr1 = np.arange(1,7)
arr2 = np.linspace(1, 10, num=5)

np.savez('./assets/test', arr1=arr1, arr2=arr2) # assets폴더 안에 test.npz 파일 저장됨
# 초기부터 키워드값을 넣어줘서 이후에 가져올 때 해당 키워드 이용하게 설정
# 키워드를 쓰지 않으면 arr_0, arr_1 이런식으로 키워드가 작성됨

numpy 배열을 `.csv` 파일이나 `.txt` 파일에 저장하려면 **savetxt()**를 이용하면 됩니다.

In [3]:
arr = np.arange(1, 10, step=3)
np.savetxt('./assets/numpy_test.csv', arr) # assets폴더 안에 numpy_test.csv 파일 저장됨

## 2. 객체 불러오기

In [4]:
# 단일 npy 파일 불러오기
arr = np.load('./assets/test.npy')
print(arr)

[1 2 3 4 5 6]


In [5]:
# 다중 npz 파일 불러오기
load_numpy = np.load('./assets/test.npz')
arr1 = load_numpy['arr1']
arr2 = load_numpy['arr2']
print(arr1)
print(arr2)

[1 2 3 4 5 6]
[ 1.    3.25  5.5   7.75 10.  ]


In [6]:
# loadtxt
arr = np.loadtxt('./assets/numpy_test.csv')
print(arr)

[1. 4. 7.]
